services:
    web:
      image: node:latest
      ports:
        - "443:443"
        - "80:80"
      
    mosquitto:
      image: eclipse-mosquitto:latest
      ports:
        - "1883:1883"
        - "1884:1884"
      volumes:
        - ./mosquitto/config:/mosquitto/config
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log
