services:
    web:
      image: chatapp_nico:latest
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "443:443"
        - "80:80"
      tty: true
      depends_on:
        mosquitto:
          condition: service_started
      
    mosquitto:
      image: eclipse-mosquitto:latest
      ports:
        - "1883:1883"
        - "1884:1884"
      volumes:
        - ./mosquitto/config:/mosquitto/config
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log
